import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { parseGitHubRemote, inferBasePath, detectPackageManager, detectNodeVersion, detectBuildCommand } from '../src/setup/github/detect.js';
import { generateWorkflowYaml, checkWorkflowSafety, writeWorkflowFile, WORKFLOW_PATH } from '../src/setup/github/workflow.js';
import { setupGitHubPages } from '../src/setup/github/index.js';
import { diagnoseGitHub } from '../src/setup/github/doctor.js';

test('parseGitHubRemote correctly extracts owner and repository from multiple URL formats', () => {
  // HTTPS standard
  const https1 = parseGitHubRemote('https://github.com/litepacks/screenpool.git');
  assert.strictEqual(https1.owner, 'litepacks');
  assert.strictEqual(https1.repository, 'screenpool');
  assert.strictEqual(https1.isGitHub, true);

  // HTTPS without .git
  const https2 = parseGitHubRemote('https://github.com/facebook/react');
  assert.strictEqual(https2.owner, 'facebook');
  assert.strictEqual(https2.repository, 'react');

  // SCP / SSH syntax
  const ssh1 = parseGitHubRemote('git@github.com:vercel/next.js.git');
  assert.strictEqual(ssh1.owner, 'vercel');
  assert.strictEqual(ssh1.repository, 'next.js');

  // ssh:// syntax with port
  const ssh2 = parseGitHubRemote('ssh://git@github.com:22/tailwindlabs/tailwindcss.git');
  assert.strictEqual(ssh2.owner, 'tailwindlabs');
  assert.strictEqual(ssh2.repository, 'tailwindcss');

  // Non-GitHub URL
  const gitlab = parseGitHubRemote('https://gitlab.com/owner/repo.git');
  assert.strictEqual(gitlab.isGitHub, false);
});

test('inferBasePath handles normal repositories, user pages, and custom domains', () => {
  // Normal repository -> /repo/
  assert.strictEqual(inferBasePath('litepacks', 'screenpool', {}), '/screenpool/');

  // User / Org page (owner.github.io) -> /
  assert.strictEqual(inferBasePath('litepacks', 'litepacks.github.io', {}), '/');
  assert.strictEqual(inferBasePath('MyUser', 'myuser.github.io', {}), '/');

  // Custom domain configured -> /
  assert.strictEqual(inferBasePath('litepacks', 'screenpool', { github: { customDomain: 'docs.example.com' } }), '/');
  assert.strictEqual(inferBasePath('litepacks', 'screenpool', { customDomain: 'docs.example.com' }), '/');
});

test('generateWorkflowYaml creates valid workflow for npm, pnpm, yarn, and bun', () => {
  // npm
  const npmYaml = generateWorkflowYaml({
    branch: 'main',
    packageManager: 'npm',
    nodeVersion: '22',
    buildCommand: 'npm run docs:build',
    outputDir: 'dist'
  });
  assert.match(npmYaml, /# Generated by Docboot/);
  assert.match(npmYaml, /branches:\s+- main/);
  assert.match(npmYaml, /run: npm ci/);
  assert.match(npmYaml, /run: npm run docs:build/);
  assert.match(npmYaml, /path: dist/);
  assert.match(npmYaml, /actions\/deploy-pages@v4/);

  // pnpm
  const pnpmYaml = generateWorkflowYaml({
    branch: 'master',
    packageManager: 'pnpm',
    nodeVersion: '20',
    buildCommand: 'pnpm run docs:build',
    outputDir: 'site'
  });
  assert.match(pnpmYaml, /pnpm\/action-setup@v4/);
  assert.match(pnpmYaml, /run: pnpm install --frozen-lockfile/);
  assert.match(pnpmYaml, /path: site/);

  // bun
  const bunYaml = generateWorkflowYaml({
    branch: 'main',
    packageManager: 'bun',
    nodeVersion: '22',
    buildCommand: 'bun run docs:build',
    outputDir: 'dist'
  });
  assert.match(bunYaml, /oven-sh\/setup-bun@v2/);
  assert.match(bunYaml, /run: bun install --frozen-lockfile/);
});

test('setupGitHubPages dry-run preview and safety overwrite check', async () => {
  const tmpDir = path.join(process.cwd(), 'scratch', 'test-setup-' + Date.now());
  fs.mkdirSync(path.join(tmpDir, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(tmpDir, 'docs', 'index.md'), '# Home');

  const mockLogger = { log: () => {} };

  // 1. Dry run
  const dryRunResult = await setupGitHubPages({
    rootDir: tmpDir,
    config: { docsDir: path.join(tmpDir, 'docs'), outDir: path.join(tmpDir, 'dist') },
    dryRun: true,
    logger: mockLogger
  });
  assert.strictEqual(dryRunResult.success, true);
  assert.strictEqual(dryRunResult.dryRun, true);
  assert.strictEqual(fs.existsSync(path.join(tmpDir, WORKFLOW_PATH)), false);

  // 2. Real setup
  const setupResult = await setupGitHubPages({
    rootDir: tmpDir,
    config: { docsDir: path.join(tmpDir, 'docs'), outDir: path.join(tmpDir, 'dist') },
    dryRun: false,
    logger: mockLogger
  });
  assert.strictEqual(setupResult.success, true);
  assert.strictEqual(fs.existsSync(path.join(tmpDir, WORKFLOW_PATH)), true);

  // 3. Re-run on generated file succeeds (has marker)
  const rerunResult = await setupGitHubPages({
    rootDir: tmpDir,
    config: { docsDir: path.join(tmpDir, 'docs'), outDir: path.join(tmpDir, 'dist') },
    dryRun: false,
    force: false,
    logger: mockLogger
  });
  assert.strictEqual(rerunResult.success, true);

  // 4. Overwriting custom workflow without marker requires --force
  fs.writeFileSync(path.join(tmpDir, WORKFLOW_PATH), '# Custom user workflow');
  const blockedResult = await setupGitHubPages({
    rootDir: tmpDir,
    config: { docsDir: path.join(tmpDir, 'docs'), outDir: path.join(tmpDir, 'dist') },
    dryRun: false,
    force: false,
    logger: mockLogger
  });
  assert.strictEqual(blockedResult.success, false);
  assert.match(blockedResult.reason, /already exists/);

  // With force -> succeeds
  const forcedResult = await setupGitHubPages({
    rootDir: tmpDir,
    config: { docsDir: path.join(tmpDir, 'docs'), outDir: path.join(tmpDir, 'dist') },
    dryRun: false,
    force: true,
    logger: mockLogger
  });
  assert.strictEqual(forcedResult.success, true);

  // 5. Doctor diagnostics
  const docResult = diagnoseGitHub(tmpDir, { docsDir: path.join(tmpDir, 'docs'), outDir: path.join(tmpDir, 'dist') });
  assert.ok(Array.isArray(docResult.passes));
  assert.ok(docResult.passes.some(p => p.includes('Workflow file')));

  // Clean up
  fs.rmSync(tmpDir, { recursive: true, force: true });
});
