import fs from 'node:fs';
import path from 'node:path';

export const WORKFLOW_PATH = '.github/workflows/docs.yml';
export const GENERATED_MARKER = '# Generated by Docboot';

/**
 * Generates the GitHub Pages workflow YAML string based on detected environment.
 * @param {object} env
 * @returns {string}
 */
export function generateWorkflowYaml(env) {
  const { branch, packageManager, nodeVersion, buildCommand, outputDir } = env;

  let installSteps = '';

  if (packageManager === 'pnpm') {
    installSteps = `      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile`;
  } else if (packageManager === 'yarn') {
    installSteps = `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable`;
  } else if (packageManager === 'bun') {
    installSteps = `      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile`;
  } else {
    // Default: npm
    installSteps = `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci`;
  }

  return `${GENERATED_MARKER}
name: Deploy Docs

on:
  push:
    branches:
      - ${branch}
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

${installSteps}

      - name: Build documentation
        run: ${buildCommand}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${outputDir || 'dist'}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;
}

/**
 * Checks whether the workflow file can be safely written.
 * @param {string} rootDir
 * @param {boolean} force
 * @returns {{ canWrite: boolean, reason?: string, isExisting: boolean }}
 */
export function checkWorkflowSafety(rootDir = process.cwd(), force = false) {
  const fullPath = path.join(rootDir, WORKFLOW_PATH);
  if (!fs.existsSync(fullPath)) {
    return { canWrite: true, isExisting: false };
  }

  if (force) {
    return { canWrite: true, isExisting: true };
  }

  const existingContent = fs.readFileSync(fullPath, 'utf-8');
  if (existingContent.includes(GENERATED_MARKER) || existingContent.includes('# Generated by Docup')) {
    return { canWrite: true, isExisting: true };
  }

  return {
    canWrite: false,
    isExisting: true,
    reason: `⚠ ${WORKFLOW_PATH} already exists and was not generated by Docboot.\nUse --force to overwrite.`
  };
}

/**
 * Writes the workflow file to disk.
 * @param {string} rootDir
 * @param {string} yamlContent
 */
export function writeWorkflowFile(rootDir = process.cwd(), yamlContent = '') {
  const fullPath = path.join(rootDir, WORKFLOW_PATH);
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(fullPath, yamlContent, 'utf-8');
}
