import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { detectGitRemote, parseGitHubRemote, inferBasePath } from '../setup/github/detect.js';

export function normalizeBase(base) {
  if (!base || base === '/' || base === '.') return '/';
  let b = String(base).trim().replace(/\\/g, '/');
  if (!b.startsWith('/')) b = '/' + b;
  if (!b.endsWith('/')) b = b + '/';
  return b;
}

export function withBase(url, base = '/') {
  if (!url) return '';
  const trimmed = String(url).trim();
  if (
    trimmed.startsWith('http://') ||
    trimmed.startsWith('https://') ||
    trimmed.startsWith('//') ||
    trimmed.startsWith('mailto:') ||
    trimmed.startsWith('tel:') ||
    trimmed.startsWith('#') ||
    trimmed.startsWith('data:')
  ) {
    return trimmed;
  }
  const normalizedBase = normalizeBase(base);
  if (trimmed === '/' || trimmed === '') return normalizedBase;
  const cleanPath = trimmed.replace(/^\/+/, '');
  return normalizedBase + cleanPath;
}

export const DEFAULT_CONFIG = {
  title: 'Documentation',
  description: 'Ultra-fast documentation generated by Docboot',
  docs: './docs',
  out: './dist',
  base: '/',
  siteUrl: '',
  repo: '',
  logo: null,
  port: 3000,
  host: 'localhost',
  sidebar: null,
  clean: false,
  theme: {
    preset: 'zinc',
    defaultMode: 'system',
    themeToggle: true,
    presetMenu: true,
    fontSizeControl: true
  },
  search: {
    boost: {
      title: 5,
      headings: 3,
      section: 2,
      text: 1
    },
    fuzzy: 0.2,
    prefix: true,
    maxResults: 10,
    minQueryLength: 2
  },
  embeds: {
    allowedDomains: [
      'codesandbox.io',
      'stackblitz.com',
      'youtube.com',
      'www.youtube.com',
      'youtube-nocookie.com',
      'www.youtube-nocookie.com',
      'youtu.be',
      'vimeo.com',
      'player.vimeo.com',
      'codepen.io'
    ]
  },
  footer: {
    pageMeta: true,
    created: true,
    updated: true,
    editLink: true,
    version: true,
    commit: false,
    buildDuration: false,
    branding: true,
    links: []
  }
};

const CONFIG_FILES = [
  'docboot.config.js',
  'docboot.config.mjs',
  'docboot.config.cjs',
  'docboot.config.json',
  'docboot.js',
  'docs.config.js',
  'docs.config.json'
];

/**
 * Loads user config if present, or returns default zero-config.
 * @param {string} rootDir Base directory to search config in
 * @param {object} cliOverrides Overrides from CLI flags
 */
export async function loadConfig(rootDir = process.cwd(), cliOverrides = {}) {
  let userConfig = {};
  let configFile = null;

  for (const filename of CONFIG_FILES) {
    const filePath = path.resolve(rootDir, filename);
    if (fs.existsSync(filePath)) {
      configFile = filePath;
      break;
    }
  }

  // Also check inside docs/ directory if rootDir doesn't have it
  if (!configFile) {
    for (const filename of CONFIG_FILES) {
      const filePath = path.resolve(rootDir, 'docs', filename);
      if (fs.existsSync(filePath)) {
        configFile = filePath;
        break;
      }
    }
  }

  if (configFile) {
    try {
      if (configFile.endsWith('.json')) {
        const content = fs.readFileSync(configFile, 'utf-8');
        userConfig = JSON.parse(content);
      } else {
        const fileUrl = pathToFileURL(configFile).href;
        const module = await import(`${fileUrl}?t=${Date.now()}`);
        userConfig = module.default || module;
      }
    } catch (err) {
      console.warn(`[docboot] Warning: Failed to load config from ${configFile}:`, err.message);
    }
  }

  // Resolve directories
  let docsDir = cliOverrides.dir || userConfig.docs || DEFAULT_CONFIG.docs;
  let absDocsDir = path.resolve(rootDir, docsDir);

  if (!fs.existsSync(absDocsDir)) {
    const fallbackDocs = path.resolve(rootDir, 'docs');
    if (fs.existsSync(fallbackDocs)) {
      absDocsDir = fallbackDocs;
    } else {
      absDocsDir = rootDir;
    }
  }

  // Extract site title from folder name if default
  let siteTitle = userConfig.title || DEFAULT_CONFIG.title;
  if (siteTitle === DEFAULT_CONFIG.title) {
    const parentDirName = path.basename(rootDir);
    if (parentDirName && parentDirName !== '.' && parentDirName !== 'docs') {
      siteTitle = parentDirName
        .split('-')
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ');
    }
  }

  const mergedSearch = {
    ...DEFAULT_CONFIG.search,
    ...(userConfig.search || {}),
    boost: {
      ...DEFAULT_CONFIG.search.boost,
      ...(userConfig.search?.boost || {})
    }
  };

  const repoUrl = cliOverrides.repo || userConfig.repo || DEFAULT_CONFIG.repo || '';

  let mergedEditLink = null;
  const userEditLink = cliOverrides.editLink !== undefined ? cliOverrides.editLink : userConfig.editLink;
  if (userEditLink) {
    if (typeof userEditLink === 'string') {
      mergedEditLink = { pattern: userEditLink, text: 'Edit this page on GitHub' };
    } else if (typeof userEditLink === 'object') {
      mergedEditLink = {
        pattern: userEditLink.pattern || (repoUrl ? `${repoUrl.replace(/\/$/, '')}/edit/main/docs/:path` : ''),
        text: userEditLink.text || 'Edit this page on GitHub'
      };
    } else if (userEditLink === true && repoUrl) {
      mergedEditLink = {
        pattern: `${repoUrl.replace(/\/$/, '')}/edit/main/docs/:path`,
        text: 'Edit this page on GitHub'
      };
    }
  }

  let mergedSourceLink = null;
  const userSourceLink = cliOverrides.sourceLink !== undefined ? cliOverrides.sourceLink : userConfig.sourceLink;
  if (userSourceLink) {
    if (typeof userSourceLink === 'string') {
      mergedSourceLink = { pattern: userSourceLink, text: 'View source' };
    } else if (typeof userSourceLink === 'object') {
      mergedSourceLink = {
        pattern: userSourceLink.pattern || (repoUrl ? `${repoUrl.replace(/\/$/, '')}/blob/main/docs/:path` : ''),
        text: userSourceLink.text || 'View source'
      };
    } else if (userSourceLink === true && repoUrl) {
      mergedSourceLink = {
        pattern: `${repoUrl.replace(/\/$/, '')}/blob/main/docs/:path`,
        text: 'View source'
      };
    }
  }

  // Base Path calculation
  let rawBase = cliOverrides.base || userConfig.base || process.env.DOCBOOT_BASE || process.env.BASE_PATH || '';
  if (!rawBase) {
    if (process.env.GITHUB_REPOSITORY && !userConfig.github?.customDomain && !userConfig.customDomain) {
      const [ghOwner, ghRepo] = process.env.GITHUB_REPOSITORY.split('/');
      rawBase = inferBasePath(ghOwner, ghRepo, userConfig);
    } else if (repoUrl && (repoUrl.includes('github.com') || repoUrl.includes('git@github.com'))) {
      const parsed = parseGitHubRemote(repoUrl);
      if (parsed?.owner && parsed?.repository) {
        rawBase = inferBasePath(parsed.owner, parsed.repository, userConfig);
      }
    }
  }
  const base = normalizeBase(rawBase || '/');

  const merged = {
    ...DEFAULT_CONFIG,
    ...userConfig,
    ...cliOverrides,
    base,
    title: siteTitle,
    repo: repoUrl,
    editLink: mergedEditLink,
    sourceLink: mergedSourceLink,
    configFile,
    rootDir,
    docsDir: absDocsDir,
    outDir: path.resolve(rootDir, cliOverrides.out || userConfig.out || DEFAULT_CONFIG.out),
    cacheDir: path.resolve(rootDir, cliOverrides.cacheDir || userConfig.cacheDir || '.docboot'),
    port: cliOverrides.port || userConfig.port || DEFAULT_CONFIG.port,
    host: cliOverrides.host || userConfig.host || DEFAULT_CONFIG.host,
    theme: {
      ...DEFAULT_CONFIG.theme,
      ...(userConfig.theme || {}),
      ...(cliOverrides.theme || {})
    },
    footer: {
      ...DEFAULT_CONFIG.footer,
      ...(userConfig.footer || {}),
      ...(cliOverrides.footer || {})
    },
    search: mergedSearch
  };

  return merged;
}
