import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

export const DEFAULT_CONFIG = {
  title: 'Documentation',
  description: 'Ultra-fast documentation generated by Docboot',
  docs: './docs',
  out: './dist',
  siteUrl: '',
  repo: '',
  logo: null,
  port: 3000,
  host: 'localhost',
  sidebar: null,
  clean: false,
  search: {
    boost: {
      title: 5,
      headings: 3,
      section: 2,
      text: 1
    },
    fuzzy: 0.2,
    prefix: true,
    maxResults: 10,
    minQueryLength: 2
  },
  embeds: {
    allowedDomains: [
      'codesandbox.io',
      'stackblitz.com',
      'youtube.com',
      'www.youtube.com',
      'youtube-nocookie.com',
      'www.youtube-nocookie.com',
      'youtu.be',
      'vimeo.com',
      'player.vimeo.com',
      'codepen.io'
    ]
  }
};

const CONFIG_FILES = [
  'docboot.config.js',
  'docboot.config.mjs',
  'docboot.config.cjs',
  'docboot.config.json',
  'docboot.js',
  'docs.config.js',
  'docs.config.json'
];

/**
 * Loads user config if present, or returns default zero-config.
 * @param {string} rootDir Base directory to search config in
 * @param {object} cliOverrides Overrides from CLI flags
 */
export async function loadConfig(rootDir = process.cwd(), cliOverrides = {}) {
  let userConfig = {};
  let configFile = null;

  for (const filename of CONFIG_FILES) {
    const filePath = path.resolve(rootDir, filename);
    if (fs.existsSync(filePath)) {
      configFile = filePath;
      break;
    }
  }

  // Also check inside docs/ directory if rootDir doesn't have it
  if (!configFile) {
    for (const filename of CONFIG_FILES) {
      const filePath = path.resolve(rootDir, 'docs', filename);
      if (fs.existsSync(filePath)) {
        configFile = filePath;
        break;
      }
    }
  }

  if (configFile) {
    try {
      if (configFile.endsWith('.json')) {
        const content = fs.readFileSync(configFile, 'utf-8');
        userConfig = JSON.parse(content);
      } else {
        const fileUrl = pathToFileURL(configFile).href;
        const module = await import(`${fileUrl}?t=${Date.now()}`);
        userConfig = module.default || module;
      }
    } catch (err) {
      console.warn(`[docboot] Warning: Failed to load config from ${configFile}:`, err.message);
    }
  }

  // Resolve directories
  let docsDir = cliOverrides.dir || userConfig.docs || DEFAULT_CONFIG.docs;
  let absDocsDir = path.resolve(rootDir, docsDir);

  if (!fs.existsSync(absDocsDir)) {
    const fallbackDocs = path.resolve(rootDir, 'docs');
    if (fs.existsSync(fallbackDocs)) {
      absDocsDir = fallbackDocs;
    } else {
      absDocsDir = rootDir;
    }
  }

  // Extract site title from folder name if default
  let siteTitle = userConfig.title || DEFAULT_CONFIG.title;
  if (siteTitle === DEFAULT_CONFIG.title) {
    const parentDirName = path.basename(rootDir);
    if (parentDirName && parentDirName !== '.' && parentDirName !== 'docs') {
      siteTitle = parentDirName
        .split('-')
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ');
    }
  }

  const mergedSearch = {
    ...DEFAULT_CONFIG.search,
    ...(userConfig.search || {}),
    boost: {
      ...DEFAULT_CONFIG.search.boost,
      ...(userConfig.search?.boost || {})
    }
  };

  const repoUrl = userConfig.repo || cliOverrides.repo || DEFAULT_CONFIG.repo || '';

  let mergedEditLink = null;
  const userEditLink = userConfig.editLink ?? cliOverrides.editLink;
  if (userEditLink) {
    if (typeof userEditLink === 'string') {
      mergedEditLink = { pattern: userEditLink, text: 'Edit this page on GitHub' };
    } else if (typeof userEditLink === 'object') {
      mergedEditLink = {
        pattern: userEditLink.pattern || (repoUrl ? `${repoUrl.replace(/\/$/, '')}/edit/main/docs/:path` : ''),
        text: userEditLink.text || 'Edit this page on GitHub'
      };
    } else if (userEditLink === true && repoUrl) {
      mergedEditLink = {
        pattern: `${repoUrl.replace(/\/$/, '')}/edit/main/docs/:path`,
        text: 'Edit this page on GitHub'
      };
    }
  }

  let mergedSourceLink = null;
  const userSourceLink = userConfig.sourceLink ?? cliOverrides.sourceLink;
  if (userSourceLink) {
    if (typeof userSourceLink === 'string') {
      mergedSourceLink = { pattern: userSourceLink, text: 'View source' };
    } else if (typeof userSourceLink === 'object') {
      mergedSourceLink = {
        pattern: userSourceLink.pattern || (repoUrl ? `${repoUrl.replace(/\/$/, '')}/blob/main/docs/:path` : ''),
        text: userSourceLink.text || 'View source'
      };
    } else if (userSourceLink === true && repoUrl) {
      mergedSourceLink = {
        pattern: `${repoUrl.replace(/\/$/, '')}/blob/main/docs/:path`,
        text: 'View source'
      };
    }
  }

  const merged = {
    ...DEFAULT_CONFIG,
    ...userConfig,
    ...cliOverrides,
    title: siteTitle,
    repo: repoUrl,
    editLink: mergedEditLink,
    sourceLink: mergedSourceLink,
    configFile,
    rootDir,
    docsDir: absDocsDir,
    outDir: path.resolve(rootDir, cliOverrides.out || userConfig.out || DEFAULT_CONFIG.out),
    cacheDir: path.resolve(rootDir, cliOverrides.cacheDir || userConfig.cacheDir || '.docboot'),
    port: cliOverrides.port || userConfig.port || DEFAULT_CONFIG.port,
    host: cliOverrides.host || userConfig.host || DEFAULT_CONFIG.host,
    search: mergedSearch
  };

  return merged;
}
